-- CREATE DATABASE mpft;
--
-- CREATE USER mpft WITH ENCRYPTED PASSWORD 'mpft';
--
-- ALTER DATABASE mpft OWNER TO mpft;
--
-- GRANT ALL PRIVILEGES ON DATABASE mpft to mpft;
--
-- CREATE SCHEMA s3_connection AUTHORIZATION mpft;
--
-- GRANT USAGE ON SCHEMA s3_connection TO mpft;
--
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE s3_connection.S3_CONNECTION TO mpft;
--
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA s3_connection TO mpft;
--
-- ************************************************
-- Select mpft database
-- ************************************************
-- \c mpft;
--


CREATE TABLE s3_connection.S3_CONNECTION
(
    ID                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CONNECTION_ID               UUID        NOT NULL UNIQUE,
    CONNECTION_NAME             VARCHAR(64) NOT NULL UNIQUE,
    SESSION_NAME                VARCHAR(64) NOT NULL UNIQUE,
    REGION                      VARCHAR(32) NOT NULL,
    IAM_ROLE_ARN                VARCHAR(255),
    ENCRYPTED_ACCESS_KEY_ID     VARCHAR(255),
    ENCRYPTED_SECRET_ACCESS_KEY VARCHAR(255)
);


-- DROP TABLE s3_connection.S3_CONNECTION;
--
-- REVOKE ALL PRIVILEGES ON DATABASE mpft from mpft;
--
-- DROP USER mpft;
--
-- DROP DATABASE mpft;
--
-- select * from s3_connection;